### ISSUE TITLE
Storybook in README returns 404

### ISSUE THREAD

**Issue by buremba** [stoplightio/json-schema-viewer#34]
The link (https://stoplightio.github.io/json-schema-viewer) returns 404

**Comment by Gdewilde** [comment]
Any news?

**Comment by P0lip** [comment]
@buremba @Gdewilde 
Hey there! My apologies for keeping you waiting.
The problem is resolved now and the storybook can be accessed.

**Comment by Gdewilde** [comment]
Thanks!  





On Thu, Aug 29, 2019 6:19 PM, Jakub Rożek notifications@github.com  wrote:
Closed #34.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.



—Gertjan De WildeCEO & Co-founder+ 32 (0) 497 20 60 51Apideck - Take your
platform strategy to the next level
