### ISSUE TITLE
question: render `$ref` for (local) `definitions`?

### ISSUE THREAD

**Issue by evaneus** [stoplightio/json-schema-viewer#6]
Hi there, stumbled across this repo while looking for an alternative to docson.

Wondering what your plans are for rendering references to local `#definitions`? 

Unless I'm missing something it seems that currently they only show as a styled path string, without being able to view the actual definition rendered.

thx!

**Comment by marbemac** [comment]
Hi @evaneus! For right now `json-schema-viewer` expects the incoming schema to be dereferenced (outside the scope of this component). We have a pretty robust resolver over here that you could try out: https://github.com/stoplightio/json-ref-resolver. Ultimately, we plan to use the `refMap` from `json-ref-resolver` to show extra info in `json-schema-viewer` of where sub-objects came from (so that it is not completely hidden after dereferencing, and the end user can easily see which parts of the resolved object came from where). Does that make sense?

**Comment by evaneus** [comment]
That's perfect. Thanks for the info!

**Comment by marbemac** [comment]
No problem! FYI @P0lip is writing up a quick readme and (maybe?) getting our storybook examples online - look for that PR in the next day or so.
